import type { Metadata } from 'next';
import { Red_Hat_Display } from 'next/font/google';

import './globals.css';

const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // sesuaikan kebutuhan
  variable: '--font-red-hat-display',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={redHatDisplay.className}>
      <body>{children}</body>
    </html>
  );
}
